#!/usr/bin/env bun

import { Script } from "@opencode-ai/script"
import type { BunPlugin } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const generated = await import("./generate.ts")

const chromiumBidiCjsStubPlugin: BunPlugin = {
  name: "stub-chromium-bidi-cjs",
  setup(build) {
    build.onResolve({ filter: /^chromium-bidi\/lib\/cjs\// }, (args) => ({
      path: args.path,
      namespace: "chromium-bidi-cjs-stub",
    }))
    build.onLoad({ filter: /.*/, namespace: "chromium-bidi-cjs-stub" }, () => ({
      contents: "export default {}",
      loader: "js",
    }))
  },
}

const pptxWorkerBundlePath = path.join(dir, "dist", "ppt-worker", "worker.mjs")
const pptxWorkerAssetPath = path.join(dir, "dist", "ppt-worker", "worker.asset")

const buildPptxWorkerBundle = async () => {
  console.log(`Building PPT browser worker bundle`)
  await fs.promises.mkdir(path.dirname(pptxWorkerBundlePath), { recursive: true })
  const result = await Bun.build({
    target: "node",
    entrypoints: [path.join(dir, "src/office/pptx/worker.mjs")],
    outdir: path.dirname(pptxWorkerBundlePath),
    naming: "worker.mjs",
    format: "esm",
    plugins: [chromiumBidiCjsStubPlugin],
  })
  if (!result.success) throw new Error("PPT worker \u6253\u5305\u5931\u8d25")
  await fs.promises.copyFile(pptxWorkerBundlePath, pptxWorkerAssetPath)
}

const createEmbeddedSkillAssetsBundle = async () => {
  console.log(`Generating embedded skill assets bundle`)
  await buildPptxWorkerBundle()
  const SKILL_DIRS = [
    {
      name: "office-ppt",
      dir: path.join(dir, "src/skill/prompt/office-ppt"),
      extraFiles: [{ key: "pptx-worker/worker.mjs", absPath: pptxWorkerAssetPath }],
    },
    { name: "xiaohongshu-ops", dir: path.join(dir, "src/skill/prompt/xiaohongshu-ops") },
    { name: "wxgzh-ops", dir: path.join(dir, "src/skill/prompt/wxgzh-ops") },
  ]
  const entries = []
  let fileIdx = 0
  for (const { name, dir: skillDir, extraFiles } of SKILL_DIRS) {
    const extraEntries = []
    for (const extra of extraFiles ?? []) {
      const spec = path.relative(dir, extra.absPath).replaceAll("\\", "/")
      extraEntries.push({
        key: `${name}/${extra.key}`,
        spec: spec.startsWith(".") ? spec : `./${spec}`,
        idx: fileIdx++,
      })
    }
    const exists = await fs.promises.stat(skillDir).then(
      () => true,
      () => false,
    )
    if (!exists) {
      entries.push(...extraEntries)
      console.log(`  ${name}: directory not found, ${extraFiles?.length ?? 0} extra files`)
      continue
    }
    const files = (await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: skillDir })))
      .map((f) => f.replaceAll("\\", "/"))
      .filter((f) => f !== "SKILL.md" && f !== "CLAUDE.md" && !f.includes("__pycache__"))
      .sort()
    for (const file of files) {
      const absPath = path.join(skillDir, file)
      const spec = path.relative(dir, absPath).replaceAll("\\", "/")
      entries.push({ key: `${name}/${file}`, spec: spec.startsWith(".") ? spec : `./${spec}`, idx: fileIdx++ })
    }
    entries.push(...extraEntries)
    console.log(`  ${name}: ${files.length + (extraFiles?.length ?? 0)} files`)
  }
  if (entries.length === 0) return "export default {}"
  const imports = entries.map((e) => `import file_${e.idx} from ${JSON.stringify(e.spec)} with { type: "file" };`)
  const mapEntries = entries.map((e) => `  ${JSON.stringify(e.key)}: file_${e.idx},`)
  return [
    `// Generated by build-node.ts — built-in skill assets`,
    ...imports,
    `export default {`,
    ...mapEntries,
    `}`,
  ].join("\n")
}

const skillAssetsMap = await createEmbeddedSkillAssetsBundle()

await Bun.build({
  target: "node",
  entrypoints: ["./src/node.ts"],
  outdir: "./dist/node",
  format: "esm",
  sourcemap: "linked",
  external: ["jsonc-parser", "@lydell/node-pty"],
  plugins: [chromiumBidiCjsStubPlugin as any],
  define: {
    OPENCODE_MODELS_DEV: generated.modelsData,
    OPENCODE_CHANNEL: `'${Script.channel}'`,
  },
  files: {
    "opencode-web-ui.gen.ts": "",
    "opencode-skills.gen.ts": skillAssetsMap,
  },
})

console.log("Build complete")
