#!/usr/bin/env bun

import { Script } from "@opencode-ai/script"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const generated = await import("./generate.ts")

const createEmbeddedSkillAssetsBundle = async () => {
  console.log(`Generating embedded skill assets bundle`)
  const SKILL_DIRS = [
    { name: "xiaohongshu-ops", dir: path.join(dir, "src/skill/prompt/xiaohongshu-ops") },
    { name: "wxgzh-ops", dir: path.join(dir, "src/skill/prompt/wxgzh-ops") },
  ]
  const entries: { key: string; spec: string; idx: number }[] = []
  let fileIdx = 0
  for (const { name, dir: skillDir } of SKILL_DIRS) {
    const exists = await fs.promises.stat(skillDir).then(
      () => true,
      () => false,
    )
    if (!exists) {
      console.log(`  ${name}: directory not found, skipping`)
      continue
    }
    const files = (await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: skillDir })))
      .map((f) => f.replaceAll("\\", "/"))
      .filter((f) => f !== "SKILL.md" && f !== "CLAUDE.md" && !f.includes("__pycache__"))
      .sort()
    for (const file of files) {
      const absPath = path.join(skillDir, file)
      const spec = path.relative(dir, absPath).replaceAll("\\", "/")
      entries.push({ key: `${name}/${file}`, spec: spec.startsWith(".") ? spec : `./${spec}`, idx: fileIdx++ })
    }
    console.log(`  ${name}: ${files.length} files`)
  }
  if (entries.length === 0) return "export default {}"
  const imports = entries.map((e) => `import file_${e.idx} from ${JSON.stringify(e.spec)} with { type: "file" };`)
  const mapEntries = entries.map((e) => `  ${JSON.stringify(e.key)}: file_${e.idx},`)
  return [
    `// Generated by build-node.ts — built-in skill assets`,
    ...imports,
    `export default {`,
    ...mapEntries,
    `}`,
  ].join("\n")
}

const skillAssetsMap = await createEmbeddedSkillAssetsBundle()

// playwright-core@1.60 still requires historical chromium-bidi CJS subpaths.
// chromium-bidi@16 only ships ESM, which breaks Bun.build resolution.
// Browser tools use CDP/channel; BiDi modules are not loaded at runtime.
const chromiumBidiCjsStubPlugin = {
  name: "stub-chromium-bidi-cjs",
  setup(build: { onResolve: Function; onLoad: Function }) {
    build.onResolve({ filter: /^chromium-bidi\/lib\/cjs\// }, (args: { path: string }) => ({
      path: args.path,
      namespace: "chromium-bidi-cjs-stub",
    }))
    build.onLoad({ filter: /.*/, namespace: "chromium-bidi-cjs-stub" }, () => ({
      contents: "export default {}",
      loader: "js",
    }))
  },
}

await Bun.build({
  target: "node",
  entrypoints: ["./src/node.ts"],
  outdir: "./dist/node",
  format: "esm",
  sourcemap: "linked",
  external: ["jsonc-parser", "@lydell/node-pty"],
  plugins: [chromiumBidiCjsStubPlugin as any],
  define: {
    OPENCODE_MODELS_DEV: generated.modelsData,
    OPENCODE_CHANNEL: `'${Script.channel}'`,
  },
  files: {
    "opencode-web-ui.gen.ts": "",
    "opencode-skills.gen.ts": skillAssetsMap,
  },
})

console.log("Build complete")
