import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const NOVAWAY_EXPERIMENTAL = truthy("NOVAWAY_EXPERIMENTAL")
const copy = process.env["NOVAWAY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  NOVAWAY_AUTO_HEAP_SNAPSHOT: truthy("NOVAWAY_AUTO_HEAP_SNAPSHOT"),
  NOVAWAY_GIT_BASH_PATH: process.env["NOVAWAY_GIT_BASH_PATH"],
  NOVAWAY_CONFIG: process.env["NOVAWAY_CONFIG"],
  NOVAWAY_CONFIG_CONTENT: process.env["NOVAWAY_CONFIG_CONTENT"],
  NOVAWAY_DISABLE_AUTOUPDATE: truthy("NOVAWAY_DISABLE_AUTOUPDATE"),
  NOVAWAY_ALWAYS_NOTIFY_UPDATE: truthy("NOVAWAY_ALWAYS_NOTIFY_UPDATE"),
  NOVAWAY_DISABLE_PRUNE: truthy("NOVAWAY_DISABLE_PRUNE"),
  NOVAWAY_DISABLE_TERMINAL_TITLE: truthy("NOVAWAY_DISABLE_TERMINAL_TITLE"),
  NOVAWAY_SHOW_TTFD: truthy("NOVAWAY_SHOW_TTFD"),
  NOVAWAY_PERMISSION: process.env["NOVAWAY_PERMISSION"],
  NOVAWAY_DISABLE_AUTOCOMPACT: truthy("NOVAWAY_DISABLE_AUTOCOMPACT"),
  NOVAWAY_DISABLE_DEFAULT_PLUGINS: truthy("NOVAWAY_DISABLE_DEFAULT_PLUGINS"),
  NOVAWAY_DISABLE_MODELS_FETCH: truthy("NOVAWAY_DISABLE_MODELS_FETCH"),
  NOVAWAY_DISABLE_MOUSE: truthy("NOVAWAY_DISABLE_MOUSE"),
  NOVAWAY_FAKE_VCS: process.env["NOVAWAY_FAKE_VCS"],
  NOVAWAY_SERVER_PASSWORD: process.env["NOVAWAY_SERVER_PASSWORD"],
  NOVAWAY_SERVER_USERNAME: process.env["NOVAWAY_SERVER_USERNAME"],

  // Experimental
  NOVAWAY_EXPERIMENTAL_FILEWATCHER: Config.boolean("NOVAWAY_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  NOVAWAY_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("NOVAWAY_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  NOVAWAY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("NOVAWAY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  NOVAWAY_MODELS_URL: process.env["NOVAWAY_MODELS_URL"],
  NOVAWAY_MODELS_PATH: process.env["NOVAWAY_MODELS_PATH"],
  NOVAWAY_DB: process.env["NOVAWAY_DB"],

  NOVAWAY_WORKSPACE_ID: process.env["NOVAWAY_WORKSPACE_ID"],
  NOVAWAY_EXPERIMENTAL_WORKSPACES: NOVAWAY_EXPERIMENTAL || truthy("NOVAWAY_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get NOVAWAY_DISABLE_PROJECT_CONFIG() {
    return truthy("NOVAWAY_DISABLE_PROJECT_CONFIG")
  },
  get NOVAWAY_TUI_CONFIG() {
    return process.env["NOVAWAY_TUI_CONFIG"]
  },
  get NOVAWAY_CONFIG_DIR() {
    return process.env["NOVAWAY_CONFIG_DIR"]
  },
  get NOVAWAY_PURE() {
    return truthy("NOVAWAY_PURE")
  },
  get NOVAWAY_PLUGIN_META_FILE() {
    return process.env["NOVAWAY_PLUGIN_META_FILE"]
  },
  get NOVAWAY_CLIENT() {
    return process.env["NOVAWAY_CLIENT"] ?? "cli"
  },
}
